### ISSUE TITLE
[feature] Support stream of bytes

### ISSUE THREAD

**Issue by mzr** [nlfiedler/fastcdc-rs#17]
Would be great if the crate could take a (possibly async) stream of bytes, did it's own buffering, and return a stream of chunks. Or perhaps something more general like a struct implementing `Read`.

**Comment by nlfiedler** [comment]
The 3.0 release now offers a `StreamCDC` implementation that reads from a `Read` into a buffer of maximum chunk size. Hope that helps.

**Comment by nlfiedler** [comment]
Forgot to mention that the streaming support is only for the new implementations based on the original 2016 paper and the revised version from 2020. They produce different chunk boundaries. For the ronomon version, there is the not-quite-streaming `with_eof()` usage demonstrated in the unit tests. I did not write a streaming version for ronomon because I don't believe that algorithm is good enough when compared to the canonical versions. If you need a streaming version of ronomon, by all means, please submit a PR, I'm not at all opposed to it. I'm just not going to invest in ronomon anymore.
